We will use Householder reflections to produce a QR factorization of the matrix

In [1]:
A = rand(1.:9.,6,4)
m,n = size(A)

(6, 4)

Our first step is to introduce zeros below the diagonal in column 1. Define the vector 

In [2]:
z = A[:,1];

Applying the Householder definitions gives us

In [3]:
using LinearAlgebra
v = z - norm(z)*[1;zeros(m-1)]
P = I - 2/(v'*v)*(v*v')   # reflector

6×6 Array{Float64,2}:
 0.270501   0.1.1.04    0.811503    0.270501    0.180334    0.360668
 0.1.1.04   0.955421   -0.200605   -0.0668685  -0.044579   -0.089158
 0.811503  -0.200605    0.0972757  -0.300908   -0.200605   -0.401211
 0.270501  -0.0668685  -0.300908    0.899697   -0.0668685  -0.133737
 0.1.1.04  -0.044579   -0.200605   -0.0668685   0.955421   -0.089158
 0.360668  -0.089158   -0.401211   -0.133737   -0.089158    0.821684

(Julia automatically fills in an identity of the correct size for the `I` above.) By design we can use the reflector to get the zero structure we seek:

In [4]:
P*z

6-element Array{Float64,1}:
 11.090536506409418    
  0.0                  
  8.881784197001252e-16
  2.220446049250313e-16
 -5.551115123125783e-17
  0.0                  

Now we let 

In [5]:
A = P*A

6×4 Array{Float64,2}:
 11.0905       11.1807    10.9102     9.73803 
  2.22045e-16   3.46092    3.78619   -0.418455
  8.88178e-16  -0.425838   0.537838  -1.38305 
  2.22045e-16   8.19139    1.17928   -1.12768 
 -5.55112e-17   7.46092    7.78619    5.58154 
  0.0           5.92185    0.572372   5.16309 

We are set to put zeros into column 2. We must not use row 1 in any way, lest it destroy the zeros we just introduced. To put it another way, we can repeat the process we just did on the smaller submatrix

In [6]:
A[2:m,2:n]

5×3 Array{Float64,2}:
  3.46092   3.78619   -0.418455
 -0.425838  0.537838  -1.38305 
  8.19139   1.17928   -1.12768 
  7.46092   7.78619    5.58154 
  5.92185   0.572372   5.16309 

In [7]:
z = A[2:m,2];
v = z - norm(z)*[1;zeros(m-2)];
P = I - 2/(v'*v)*(v*v');   

We now apply the reflector to the submatrix.

In [8]:
A[2:m,2:n] = P*A[2:m,2:n]
A

6×4 Array{Float64,2}:
 11.0905       11.1807       10.9102    9.73803
  2.22045e-16  13.0381        6.44391   4.76465
  8.88178e-16  -1.66282e-16   0.65601  -1.15259
  2.22045e-16   7.64475e-16  -1.1.088  -5.56081
 -5.55112e-17   7.85503e-16   5.71574   1.54374
  0.0           1.61293e-15  -1.07098   1.95822

We need two more iterations of this process.

In [9]:
for j = 3:n
    z = A[j:m,j]
    v = z - norm(z)*[1;zeros(m-j)]
    P = I - 2/(v'*v)*(v*v')
    A[j:m,j:n] = P*A[j:m,j:n]
end

We have now reduced the original  to an upper triangular matrix using four orthogonal Householder reflections:

In [10]:
R = A

6×4 Array{Float64,2}:
 11.0905       11.1807       10.9102        9.73803    
  2.22045e-16  13.0381        6.44391       4.76465    
  8.88178e-16  -1.66282e-16   5.95345       2.02456    
  2.22045e-16   7.64475e-16   3.99998e-16   5.86259    
 -5.55112e-17   7.85503e-16  -1.63066e-15  -4.0386e-16 
  0.0           1.61293e-15   4.2762e-16    9.62121e-16