We will use Householder reflections to produce a QR factorization of the matrix

In [1]:
A = rand(1.:9.,6,4)
m,n = size(A)

(6, 4)

Our first step is to introduce zeros below the diagonal in column 1. Define the vector 

In [2]:
z = A[:,1];

Applying the Householder definitions gives us

In [3]:
using LinearAlgebra
v = z - norm(z)*[1;zeros(m-1)]
P = I - 2/(v'*v)*(v*v')   # reflector

6×6 Array{Float64,2}:
 0.240337   0.420589   0.300421   0.540758   0.540758   0.300421
 0.420589   0.76714   -0.166329  -0.299392  -0.299392  -0.166329
 0.300421  -0.166329   0.881194  -0.213851  -0.213851  -0.118806
 0.540758  -0.299392  -0.213851   0.615068  -0.384932  -0.213851
 0.540758  -0.299392  -0.213851  -0.384932   0.615068  -0.213851
 0.300421  -0.166329  -0.118806  -0.213851  -0.213851   0.881194

(Julia automatically fills in an identity of the correct size for the `I` above.) By design we can use the reflector to get the zero structure we seek:

In [4]:
P*z

6-element Array{Float64,1}:
 16.643316977093235     
  8.881784197001252e-16 
  4.440892098500626e-16 
  1.7763568394002505e-15
  1.7763568394002505e-15
  8.881784197001252e-16 

Now we let 

In [5]:
A = P*A

6×4 Array{Float64,2}:
 16.6433        5.58783    12.7979    6.90968
  7.77156e-16  -0.432757    2.23631   3.15731
  8.18789e-16   1.9766      5.31165   2.82665
  1.249e-15     2.15788    -1.83903   5.48797
  1.249e-15     0.157884    0.160972  2.48797
  8.88178e-16  -0.0233978   4.31165   2.82665

We are set to put zeros into column 2. We must not use row 1 in any way, lest it destroy the zeros we just introduced. To put it another way, we can repeat the process we just did on the smaller submatrix

In [6]:
A[2:m,2:n]

5×3 Array{Float64,2}:
 -0.432757    2.23631   3.15731
  1.9766      5.31165   2.82665
  2.15788    -1.83903   5.48797
  0.157884    0.160972  2.48797
 -0.0233978   4.31165   2.82665

In [7]:
z = A[2:m,2];
v = z - norm(z)*[1;zeros(m-2)];
P = I - 2/(v'*v)*(v*v');   

We now apply the reflector to the submatrix.

In [8]:
A[2:m,2:n] = P*A[2:m,2:n]
A

6×4 Array{Float64,2}:
 16.6433        5.58783      12.7979    6.90968
  7.77156e-16   2.96246       1.8523    5.53253
  8.18789e-16   4.29072e-16   5.53521   1.44386
  1.249e-15     6.36717e-16  -1.59496   3.97836
  1.249e-15     4.53158e-17   0.178829  2.37752
  8.88178e-16  -4.86034e-18   4.309     2.84302

We need two more iterations of this process.

In [9]:
for j = 3:n
    z = A[j:m,j]
    v = z - norm(z)*[1;zeros(m-j)]
    P = I - 2/(v'*v)*(v*v')
    A[j:m,j:n] = P*A[j:m,j:n]
end

We have now reduced the original  to an upper triangular matrix using four orthogonal Householder reflections:

In [10]:
R = A

6×4 Array{Float64,2}:
 16.6433        5.58783      12.7979        6.90968    
  7.77156e-16   2.96246       1.8523        5.53253    
  8.18789e-16   4.29072e-16   7.19597       1.99035    
  1.249e-15     6.36717e-16  -2.96548e-16   5.26175    
  1.249e-15     4.53158e-17   1.10622e-17  -8.78105e-16
  8.88178e-16  -4.86034e-18   1.35079e-16  -5.53514e-16