The `eigvals` command will return just the eigenvalues, as a vector. 

In [1]:
A = pi*ones(2,2)
using LinearAlgebra
lambda = eigvals(A)

2-element Array{Float64,1}:
 0.0              
 6.283185307179586

If we also want the eigenvectors (returned as the matrix $V$), we use `eigen`.

In [2]:
lambda,V = eigen(A)

Eigen{Float64,Float64,Array{Float64,2},Array{Float64,1}}
eigenvalues:
2-element Array{Float64,1}:
 0.0              
 6.283185307179586
eigenvectors:
2×2 Array{Float64,2}:
 -0.707107  0.707107
  0.707107  0.707107

We can check the fact that this is an EVD.

In [3]:
D = diagm(0=>lambda)
opnorm( A - V*D/V )      # "/V" is like "*inv(V)""

8.881784197001252e-16

Even if the matrix is not diagonalizable, `eigen` will run successfully, but the matrix ${V}$ will not be invertible.

In [4]:
lambda,V = eigen([1 1;0 1])
@show rank(V);

rank(V) = 1
